Dataset uzet sa [link](https://www.kaggle.com/datasets/shravankumar9892/image-colorization)

# Global settings

In [1]:
try:
  import google.colab
  from google.colab import output
  output.enable_custom_widget_manager()
  IN_COLAB = True
except:
  IN_COLAB = False
IN_COLAB

False

In [2]:
if IN_COLAB:
    %pip install torchvision torchaudio torch scipy numpy scikit-image lion-pytorch torchmetrics
DEBUG=False
if DEBUG:
  import os
  os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

In [3]:
dataset_path='./dataset/'
model_weights_path = './model_weights/'

In [4]:
from PIL import Image
import numpy as np
from skimage.color import rgb2lab, lab2rgb, rgb2gray
from skimage.io import imsave
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
import torch
import math, time
from tqdm.auto import tqdm
from lion_pytorch import Lion
import torch.optim.lr_scheduler as lr_scheduler
from torchmetrics.image.fid import FrechetInceptionDistance
from gc import collect
from os.path import isfile, exists
from os import remove, makedirs 
from psutil import virtual_memory
from torchvision import transforms
from warnings import warn, filterwarnings
import zipfile 
from itertools import islice
# import kaggle.api
from huggingface_hub import notebook_login

seed=42
_ = torch.manual_seed(seed)
_np = np.random.seed(seed)

if torch.cuda.is_available():
    _cuda = torch.cuda.manual_seed_all(seed)

d:\Projects\CompVisProject\.venv\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")


In [5]:
# num_classes=26
# start_ab = -128
# end_ab = 128
# bins = np.linspace(start_ab, end_ab, num=num_classes)

In [6]:
# mappings = dict()

# class_counter = 0
# for i in range(num_classes):
#   for j in range(num_classes):
#     mappings[str(i) + str(j)] = class_counter
#     class_counter += 1

In [7]:
#NOTE verovatnoce iz "Colorful Image Colorization" rada
probs = np.load('./prior_probs.npy', mmap_mode='r')
mappings = np.load('./pts_in_hull.npy', mmap_mode='r')
num_classes = len(probs)
ab_range = np.arange(-110, 120, 10)

In [8]:
np.where( np.all( mappings == [-90,50], axis=1) )[0].item()

0

In [9]:
# np.histogram2d(bins,bins,bins=26)

In [10]:
# gde_sam_stao=0
# brojac=0

In [11]:
# notebook_login()

In [12]:
# probsNotFormed = False 
# if probsNotFormed:
#   from datasets import load_dataset
#   dataset = load_dataset('imagenet-1k', 'en', split='train', streaming=True)
#   if not isfile(f'{dataset_path}distributions.npy'):
#       distros = np.memmap(f'{dataset_path}distributions.npy',mode="w+",dtype=np.ulonglong,shape=(num_classes ** 2))
#   else:
#       distros = np.memmap(f'{dataset_path}distributions.npy',dtype=np.ulonglong, mode="r+")
#   for sth in dataset:
#     if brojac != gde_sam_stao:
#       brojac+=1
#       continue
#     if np.array(sth['image']).ndim == 3:
#       lab_image = rgb2lab( (np.array(sth['image'].resize((224,224))).reshape(224,224,3))/255, channel_axis=2)
#       quantized_a = np.digitize(lab_image[:,:,1], bins=bins)-1
#       quantized_b = np.digitize(lab_image[:,:,2], bins=bins)-1
#       for i in range(224):
#         for j in range(224):
#           distros[mappings[str(quantized_a[i,j]) + str(quantized_b[i,j])]] += 1
#           brojac+=1
#           gde_sam_stao = brojac

#   distros.flush()
#   del distros

In [13]:
# distros = np.memmap(f'{dataset_path}distributions.npy',dtype=np.ulonglong, mode="r")
# probs = distros / sum(distros)

In [14]:
# indices_larger_than_0 = np.where( probs > 0)
# probs = indices_larger_than_0[0]
# num_classes = len(probs)

In [15]:
if not isfile('./archive.zip'):
    kaggle.api.authenticate()
    kaggle.api.dataset_download_files('shravankumar9892/image-colorization',path='.',unzip=False)

if not exists(dataset_path):
    makedirs(dataset_path, exist_ok=True)
if not exists(model_weights_path):
    makedirs(model_weights_path, exist_ok=True)

if not exists(dataset_path+'ab') and not exists(dataset_path+'l'):
    with zipfile.ZipFile('./archive.zip', 'r') as zip_ref:
        zip_ref.extractall(dataset_path)

# Loading data

# Funkcija za konvertovanje slike iz sRGB u L\*a\*b\*

In [16]:
def convert_rgb_to_lab(image: np.ndarray) -> np.ndarray: 
    """
    Ova funkcija konvertuje image iz sRGB prostora u L*a*b* prostor.
    
    Parameters
    -----------
    image : np.NDArray, shape: Tuple[int,int,int[,int]]
        Slika(ili slike) treba da bude 3D/4D numpy array, gde je prva dimenzija redni broj slike(ako ih ima vise), druga dimenzija broj kanala, a treca i cetvrta sirina x visina. 
    
    Returns
    -------
        Returns a `np.ndarray` of shape (num_of_images, 3, height, width) if `image` is 4D, else if `image` is 3D it returns (3, height, width).
    """
    assert 3 in image.shape, f"Nije pronadjena nijedna dimenzija koja je =3"
    assert 3 <= image.ndim <= 4, f"Ocekivani broj dimenzija ulaznog parametra je izmedju 3 i 4(inclusive), a dobijeno je {image.ndim}"
    assert np.all( (image >= 0) & (image <= 255 )), f"Ocekivano da slike budu RGB formata s opsegom [0,255], to nije dobijeno ovde..."
    if np.all( (image == 0) | (image == 255)):
        warn(f"Postoje slike koje su iskljucivo bele ili crne")
    if image.ndim == 3:
        assert image.shape[0] == 3, f"Pogresna dimenzija na poziciji shape[0], ocekivano 3, dobijeno {image.shape[0]}"
        lab_image = rgb2lab(1.0/255*image, channel_axis=0)
        lab_image[1:] = lab_image[1:] / 128
        # X = lab_image[0]
        # Y = lab_image[1:]
        assert np.all( ( lab_image[0] >= 0) & ( lab_image[0] <= 100) ), f"U L* kanalu pronadjeno nedozvoljenih vrednosti"
        assert np.all( ( lab_image[1:] >= -1) & ( lab_image[1:] <= 1) ), f"U a*b* kanalima pronadjeno nedozvoljenih vrednosti"
        if np.all( (lab_image[0] == 0.0) | (lab_image[0] == 100.0) | (lab_image[1:] == 1.0) | (lab_image[1:] == -1.0 ) | (lab_image[1:] == 0.0 )):
            warn(f"Potencijalno postoje slike koje su iskljucivo bele ili crne")
    elif image.ndim == 4:
        assert image.shape[1] == 3, f"Pogresna dimenzija na poziciji shape[1], ocekivano 3, dobijeno {image.shape[1]}"
        lab_image = rgb2lab(1.0/255*image, channel_axis=1)
        lab_image[:,1:] = lab_image[:,1:] / 128
        assert np.all( (lab_image[:,0:1] >= 0 ) & (lab_image[:,0:1] <= 100 )), f"U L* kanalu pronadjeno nedozvoljenih vrednosti"
        assert np.all( (lab_image[:,1:] >= -1 ) & (lab_image[:,1:] <= 1 )), f"U a*b* kanalima pronadjeno nedozvoljenih vrednosti"
        if np.all( (lab_image[:,0:1] == 0.0) | (lab_image[:,0:1] == 100.0) | (lab_image[:,1:] == 1.0) | (lab_image[:,1:] == -1.0 ) | (lab_image[:,1:] == 0.0 ) ):
            warn(f"Potencijalno postoje slike koje su iskljucivo bele ili crne")
        # X = lab_image[:,0]
        # Y = lab_image[:,1:]
    return lab_image
    # Y /= 128
    # X = X.reshape(1 if image.ndim == 3 else image.shape[0], 1, image.shape[1 if image.ndim == 3 else 2], image.shape[2 if image.ndim == 3 else 3])
    # assert np.all( (X >= 0) & (X <= 100) , axis=(1,2) if image.ndim == 3 else (2,3)).any(), f"U L* kanalu pronadjeno nedozvoljenih vrednosti"
    # Y = Y.reshape(1 if image.ndim == 3 else image.shape[0], 2, image.shape[1 if image.ndim == 3 else 2], image.shape[2 if image.ndim == 3 else 3])
    # assert np.all( (Y >= -1) & (Y <= 1) ), f"U L* kanalu pronadjeno nedozvoljenih vrednosti"
    # return X,Y

In [17]:
# NOTE: testiramo ispravnost
# img = convert_rgb_to_lab(image.reshape(1,3,400,400))
# X,Y = img[:,0:1,:,:], img[:,1:,:,:]

# Funkcija za reverse convert

In [18]:
def convert_lab_to_rgb(image: np.ndarray, denormalize=False) -> np.ndarray:
    """
    Ova funkcija konvertuje iz L*a*b* prostora u sRGB prostor.

    Parameters
    ----------
    image: np.NDArray, shape: Tuple[int,int,int[,int]]
        Slika(ili slike) treba da bude 3D/4D numpy array, gde je prva dimenzija redni broj slike(ako ih ima vise), druga dimenzija oznacava kanal(L*, a* ili b*), a treca i cetvrta sirina x visina. L* kanal mora da sadrzi vrednosti od 0 do 100, dok a* i b* moraju imati vrednosti izmedju -128 i 127.
    denormalize : boolean=False
        Da li denormalizovati podatke. Ako je denormalize=`True`, onda se koristi sRGB opseg [0,255], u protivnom se koristi [0,1]

    Returns
    -------
    Vraca nam sliku(ili slike) u `numpy.ndarray` formatu.   
    """
    assert 3 in image.shape, f"Nije pronadjena nijedna dimenzija koja je =3"
    assert 3 <= image.ndim <= 4, f"Ocekivani broj dimenzija ulaznog parametra je izmedju 3 i 4(inclusive), a dobijeno je {image.ndim}"
    if image.ndim == 3:
        assert image.shape[0] == 3, f"Pogresna dimenzija na poziciji shape[0], ocekivano 3, dobijeno {image.shape[0]}"
        assert np.all( (image[0] >= 0.0) & ( image[0] <= 100.0) & (image[1:] >= -128) & ( image[1:] <= 128) )
        rgb_image = lab2rgb(image, channel_axis=0)
    elif image.ndim == 4:
        assert image.shape[1] == 3, f"Pogresna dimenzija na poziciji shape[1], ocekivano 3, dobijeno {image.shape[1]}"
        print()
        assert np.all( (image[:,0:1] >= 0.0) & ( image[:,0:1] <= 100.0) & (image[:,1:] >= -128) & ( image[:,1:] <= 128) )
        rgb_image = lab2rgb(image, channel_axis=1)
    # rgb_image = rgb_image.reshape(1 if image.ndim == 3 else image.shape[0], 3, image.shape[1 if image.ndim == 3 else 2], image.shape[2 if image.ndim == 3 else 3])
    assert np.all( (rgb_image >= 0) & (rgb_image <=1.0)), f"Ocekivani opseg RGB vrednosti 0-1 je prekrsen"
    if np.all( (rgb_image == 0.0) | (rgb_image == 1.0)):
        warn(f"Postoje slike koje su iskljucivo crne ili bele")
    return rgb_image if not denormalize else (rgb_image * 255).astype(np.uint8)

In [19]:
# NOTE: testiramo ispravnost
# imgs_back_2rgb = convert_lab_to_rgb( np.concatenate( (X,Y), axis=1))

In [20]:
def load_data(mmap_mode = None, percentage:int = 0.7, shape=(25000,3,224,224), returnJoinedInstead=False):
    """
    Treba da ucita podatke sa diska kao memory map. Memory-mapped podaci se ne ucitavaju svi u memoriju, vec se ucitavaju sa diska direktno po potrebi. 

    Parameters
    ----------
    mmap_mode : str | None
        U kom rezimu treba da ucitamo finalni dataset. Za vise videti [link](https://numpy.org/doc/stable/reference/generated/numpy.memmap.html#numpy.memmap). Ako je `None`, ucitace ceo dataset u memoriju.
    percentage : int = 0.7
        Koliko procenata dostupne sistemske memorije zelimo iskoristiti za konverziju.
    
    Returns
    -------
        Ucitani L*a*b* dataset `np.ndarray`, ako je mmap_mode=`None`, u protivnom vraca `memmap` i cita se sa diska.
    """
    should_delete_dataset=False
    assert 0.1 < percentage < 0.9, f"Ocekivan opseg procenata [10%,90%], dobijeno {percentage}"
    if isfile(dataset_path + 'lab_dataset.npy'):
        return np.memmap(dataset_path + 'lab_dataset.npy',mode=mmap_mode, shape=shape,dtype="float16") if not returnJoinedInstead else np.load(dataset_path + 'joined_dataset.npy', mmap_mode='r')
    elif isfile(dataset_path + 'joined_dataset.npy'):
        joined_dataset = np.load(dataset_path + 'joined_dataset.npy', mmap_mode='r') # ucitavamo zdruzeni dataset
        dataset_shape = joined_dataset.shape
        dataset = np.memmap(dataset_path + 'lab_dataset.npy', mode="w+", shape=(dataset_shape[0],3,224,224), dtype="float16") # kreiramo memory-mapped fajl za finalni dataset (7 GB).
        available_system_memory_in_GBs = virtual_memory().available/1024**3
        how_much_memory_to_reserve_for_conversion_in_GBs = available_system_memory_in_GBs * percentage
        converted_image_size_in_GBs = dataset_shape[0] * 8 * 3 * 224 * 224 / 1024**3  # 28 GB u sustini ako sve odjednom konvertujem.
        print(f"Dostupna memorija za konverziju slika {how_much_memory_to_reserve_for_conversion_in_GBs}")
        print(f"Memorija potrebna za konverziju slika {converted_image_size_in_GBs}")

        try:
            if how_much_memory_to_reserve_for_conversion_in_GBs - converted_image_size_in_GBs >= 1: # Ostavljamo 1 GB overhead-a
                image = convert_rgb_to_lab(joined_dataset)
                dataset[:] = image
            else: # U protivnom koristimo batched obradu.
                batch_size = int( (how_much_memory_to_reserve_for_conversion_in_GBs-1)*dataset_shape[0] / (32*converted_image_size_in_GBs) ) # -1 zbog memory overheada. 32 jer rgb2lab koristi float64...
                print(f"Batch size:\t{batch_size}")
                assert batch_size > 1, f"Nemate dovoljno memorije za ovakvu operaciju, ocekivano je da batch_size bude veci od 1, ali je {batch_size}"
                for i in range(0, dataset_shape[0], batch_size+1):
                    dataset[i:i+batch_size] = convert_rgb_to_lab( joined_dataset[i:i+batch_size] )
                dataset[i:] = convert_rgb_to_lab( joined_dataset[i:] )
        except MemoryError as e:
            print(f"Doslo je do greske:\n{e}")
            should_delete_dataset = True
        except Exception as e:
            should_delete_dataset = True
            print(e)
        finally:
            dataset.flush()
            print("Flushed!")
            del dataset, joined_dataset
            collect()
            if should_delete_dataset:
                remove(dataset_path + 'lab_dataset.npy')
                return

        print("Kreirani finalni dataset")
        return load_data(mmap_mode, percentage, dataset_shape)
    else:
        X = np.load(dataset_path + 'l/gray_scale.npy',mmap_mode='r').reshape(25000,1,224,224)
        y_file_to_load = [ f'ab/ab/ab{i}.npy' for i in range(1,4)]
        Y = np.concatenate( [ np.load(dataset_path + file) for file in y_file_to_load ], axis=0 ).reshape(25000,2,224,224)
        np.save(dataset_path + 'joined_dataset.npy', np.concatenate( (X,Y), axis=1))
        del X,Y,y_file_to_load
        collect()
        print("Kreirani zdruzeni dataset")
        return load_data(mmap_mode, percentage)

# Ucitavanje i pripremu dataseta

## Funkcija za ucitavanje i kreiranje memory-mapped dataseta

## Definisanje transformacija slika

In [21]:
# NOTE: transformacija slike nije podrzana...
# transform = transforms.Compose([
#     # transforms.ToTensor(),
#     transforms.RandomHorizontalFlip(),
#     transforms.RandomAffine(degrees=20, shear=0.2, scale=(0.8, 1.2)),
#     # transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.2),
# ])

## Klasa naseg custom dataseta

In [22]:
# definisanje custom dataseta
class IterableImageDataset(torch.utils.data.IterableDataset):
    def __init__(self, dataset_indices: list, num_of_classes:int, mappings:dict, return_joined:bool=False, transform=None, bins=None):
        """
        Inicijalizuje dataset

        Parameters
        ----------
        data_indices : list
            Koje redove iz dataseta koristimo
        transform(optional) : torchvision.Compose
            Transformacije koje koje primenjujemo nad nasim slikama.
        """
        # assert data.ndim == 4, f"Ocekivan broj dimenzija dataseta 4, dobijeno {data.ndim}"
        # assert data.shape == (data.shape[0],3,224,224), f"Ocekivan shape dataseta (25000,3,224,224), dobijeno {data.shape}"
        # assert np.all( (data >= 0) & (data <= 255)), f"Slike treba da su u RGB formatu!"
        self.data = load_data("r", returnJoinedInstead=return_joined) 
        self.is_joined = return_joined
        self.indices = dataset_indices
        self.transform = transform
        self.num_of_classes = num_of_classes
        self.mappings = mappings
        self.bins = bins

    def __len__(self):
        return len(self.data)

    def process_data(self, dataset):
        for idx in self.indices:
            img = dataset[idx]
            if self.transform:
                # if self.is_joined:
                #     img_transformed = convert_rgb_to_lab(img_transformed)
                img_transformed = self.transform(torch.as_tensor( convert_lab_to_rgb(img) if not self.is_joined else img,dtype=torch.float32))

                yield img_transformed[0].reshape(-1,224,224), map_ab_to_quantized(img_transformed[1:] * 110 , self.mappings, bins=self.bins)
            else:
                # if self.is_joined:
                img = torch.as_tensor( convert_lab_to_rgb(img) if not self.is_joined else img,dtype=torch.float32)
                yield img[0].reshape(-1,224,224), map_ab_to_quantized(img[1:] * 110, self.mappings, bins=self.bins)

    def __iter__(self):
        worker_info = torch.utils.data.get_worker_info() # NOTE ako je None, onda je single-process
        if worker_info is None:
            return iter(self.process_data(self.data))
            # return islice(map(self.process_data, iter(self.data)),0)
        total_number_of_workers = worker_info.num_workers
        worker_id = worker_info.id
        dataset_length = self.__len__()

        mapped_iterator = map(self.process_data, iter(self.data))
        # return islice(iter(self.process_data(self.data[self.indices])), worker_id, None, total_number_of_workers)
        return islice(mapped_iterator, worker_id, None, total_number_of_workers)
 
    #   lab_image = rgb2lab( (np.array(sth['image'].resize((224,224))).reshape(224,224,3))/255, channel_axis=2)
    #   quantized_a = np.digitize(lab_image[:,:,1], bins=bins)
    #   quantized_b = np.digitize(lab_image[:,:,2], bins=bins)
def map_ab_to_quantized(ab_image, mappings: np.ndarray, bins):
    output = torch.zeros((224, 224), dtype=torch.long)
    a_channel = np.digitize(ab_image[0:1], bins=bins).reshape((224,224))
    b_channel = np.digitize(ab_image[1:2], bins=bins).reshape((224,224))
    for i in range(224):
        for j in range(224):
            # output[i,j] = mappings[str(a_channel[i,j]) + str(b_channel[i,j])]
            print(np.where( np.all( mappings == [a_channel[i,j], b_channel[i,j]], axis=1)))
            print(a_channel[i,j])
            print(b_channel[i,j])
            output[i,j] = np.where( np.all( mappings == [a_channel[i,j], b_channel[i,j]], axis=1))[0].item()
    return output

## Ucitavanje podataka, podela na trening i test

In [46]:
dataset_memory_map = load_data('r')
# dataset_memory_map = load_data('r')

In [60]:
output = torch.zeros((224, 224), dtype=torch.long)
for img in dataset_memory_map:
    ab_image = torch.as_tensor(img[1:].copy(), dtype=torch.float32) * 110
    a_channel = np.digitize(ab_image[0:1], bins=ab_range).reshape((224,224))
    b_channel = np.digitize(ab_image[1:2], bins=ab_range).reshape((224,224))
    print("U kanalu a, prvi broj je: ", a_channel[0,0], " sto znaci da je u pitanju opseg: ", ab_range[a_channel[0,0]-1:a_channel[0,0]])
    print("U kbnblu b, prvi broj je: ", b_channel[0,0], " sto znbci db je u pitbnju opseg: ", ab_range[b_channel[0,0]-1:b_channel[0,0]])
    # print(b_channel.shape)
    break

[[15 11 10 10 11 12 16 15 16 15 15 15 16 15 16 14 14 15 15 15 16 15]
 [15 12 10 10 11 13 16 15 16 15 16 15 16 15 16 15 15 15 16 15 16 15]
 [14 14 11 10 11 11 15 15 16 15 15 15 16 15 16 15 15 15 16 15 16 15]
 [15 15 11 10 11 11 15 15 16 15 16 15 16 15 16 15 15 15 16 15 16 15]
 [14 15 12 10 11 10 13 15 15 15 15 15 16 15 15 15 15 12 12 15 16 15]
 [12 15 12 10 11 11 13 13 13 14 13 14 16 15 15 15 15 14 12 13 15 15]
 [11 14 13 10 11 10 13 13 14 14 14 13 14 15 16 15 15 14 13 12 15 15]
 [15 15 13 10 11 11 13 13 13 13 14 14 13 13 14 14 15 14 14 14 15 15]
 [15 11 10 10 11 11 13 13 14 13 11 13 14 13 14 12 13 14 15 15 15 14]
 [11 10 10 10 11 11 13 13 13 13 12 12 12 13 14 14 13 13 14 15 15 15]
 [12  9 10 10 10 11 12 11 13 13 12 12 13 12 12 11 13 11 13 12 13 14]
 [13 12 10 10 11 10 11 13 13 12 12 12 12 13 13 12 12 12 12 12 12 11]
 [12 12 10 10 10  9 10 13 13 13 14 12 12 11 13 11 11 10 11 12 11 12]
 [12 12 11 10 10 10 12 14 13 13 14 13 13 12 12 12 11 10 11 11 12 13]
 [13 11 10 10 10 10 14 15 13 13 14

In [24]:
# NOTE: aktiviraj globalnu booleanku da testiras ovo v
check_if_memory_map_values_valid = False 
if check_if_memory_map_values_valid:
    use_joined=False
    dataset_memory_map_test = load_data('r',returnJoinedInstead=use_joined)
    for i in range(len(dataset_memory_map_test)):
        if not use_joined:
            assert np.all( ( dataset_memory_map_test[i][0] >= 0.0 ) & ( dataset_memory_map_test[i][0]  <= 100.0 )), f"Ocekivan opseg u L* kanalu [0,100], ali red {i} u dataset_memory_map_test krsi ovo pravilo."
            assert np.all( ( dataset_memory_map_test[i][1:] >= -1.0 ) & ( dataset_memory_map_test[i][1:]  <= 1.0 )), f"Ocekivan opseg u a* i b* kanalu [-1,1], ali red {i} u dataset_memory_map_test krsi ovo pravilo."
        else:
            assert np.all( ( dataset_memory_map_test[i] >= 0 ) & ( dataset_memory_map_test[i] <= 255 )), f"Ocekivan opseg u a* i b* kanalu [-1,1], ali red {i} u dataset_memory_map_test krsi ovo pravilo."
        if not use_joined and ( np.all( (dataset_memory_map[i][0] == 0.0) | (dataset_memory_map[i][0] == 100.0)) or np.all( (dataset_memory_map[i][1:] == 0.0) | (dataset_memory_map[i][1:] == 1.0)| (dataset_memory_map[i][1:] == -1.0))):
           warn(f"Slika redni broj {i} sadrzi cudne vrednosti na L* ili a*/b* kanalima. L* treba da je [0,100](float), a a*b* [-1,1](float)") 
        elif use_joined and np.all( (dataset_memory_map[i] == 0) | (dataset_memory_map[i] == 255) ):
           warn(f"Slika redni broj {i} sadrzi cudne vrednosti na RGB kanalima, opseg treba da je [0,255](uint8).") 

    del dataset_memory_map_test

In [25]:
test_size = 0.2
validation_size = 0.15

test_length = int(test_size * dataset_memory_map.shape[0])
remaining_length = dataset_memory_map.shape[0] - test_length
validation_length = int(remaining_length * validation_size)
training_length = remaining_length - validation_length

training_length, validation_length, test_length

indices = [i for i in range(dataset_memory_map.shape[0])]

training_indices = np.random.choice(range(0, dataset_memory_map.shape[0]), size=training_length, replace=False)
validation_indices = np.random.choice(list(set(range(0, dataset_memory_map.shape[0])) - set(training_indices)), size=validation_length, replace=False)
test_indices = np.random.choice(list(set(range(0, dataset_memory_map.shape[0])) - set(training_indices) - set(validation_indices)), size=test_length, replace=False)

# training_ds = IterableImageDataset(dataset_memory_map[training_indices], transform=transform)
# validation_ds = IterableImageDataset(dataset_memory_map[validation_indices], transform=transform)
training_ds = IterableImageDataset(training_indices, mappings=mappings, num_of_classes=num_classes, bins=ab_range)
validation_ds = IterableImageDataset(validation_indices, mappings=mappings, num_of_classes=num_classes, bins=ab_range)

# Softmax Annealed mean

In [26]:
class SoftmaxAnnealedMean(torch.nn.Module):
    def __init__(self, temperature:float=0.38):
        super(SoftmaxAnnealedMean, self).__init__()
        self.temperature = temperature

    def forward(self, ground_truth, dim:int=1, isLogits:bool=True):
        """
        Sracunava annealed mean raspodele verovatnoca. Ovo koristimo da predvidjenu distribuciju mapiramo u tacku u ab prostoru.

        Parameters
        ----------
        ground_truth : torch.Tensor
            Istinitosne vrednosti za ab kanale oblika (batch_size, number_of_classes, width, height)
        dim : int
            Dimenzija po kojoj se vrsi sumiranje, ako je broj klasa na drugoj poziciji, koristiti defaultnu vrednost `dim=1`.
        isLogits : bool = True
            Da li su vrednosti u prosledjenom tenzoru logiti ili ne - ako jesu, konvertovace ih u verovatnoce automatski.
        """
        if isLogits:
            ground_truth = torch.nn.Softmax(ground_truth, dim=dim)
        return torch.exp( torch.log(ground_truth) / self.temperature ) / torch.sum( torch.exp( torch.log(ground_truth) / self.temperature ) , dim=dim)


# Model class

In [27]:
class ColorizerModel(nn.Module):
    def __init__(self, number_of_classes:int):
        super(ColorizerModel, self).__init__()
        
        self.conv1 = nn.Conv2d(1, 64, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(64, 64, kernel_size=3, padding=1, stride=2)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.conv4 = nn.Conv2d(128, 128, kernel_size=3, padding=1, stride=2)
        self.conv5 = nn.Conv2d(128, 256, kernel_size=3, padding=1)
        self.conv6 = nn.Conv2d(256, 256, kernel_size=3, padding=1, stride=2)
        self.conv7 = nn.Conv2d(256, 512, kernel_size=3, padding=1)
        self.conv8 = nn.Conv2d(512, 256, kernel_size=3, padding=1)
        self.conv9 = nn.Conv2d(256, 128, kernel_size=3, padding=1)
        self.upsample1 = nn.Upsample(scale_factor=2, mode='nearest')
        self.conv10 = nn.Conv2d(128, 64, kernel_size=3, padding=1)
        self.upsample2 = nn.Upsample(scale_factor=2, mode='nearest')
        self.conv11 = nn.Conv2d(64, 32, kernel_size=3, padding=1)
        self.upsample3 = nn.Upsample(scale_factor=2, mode='nearest')
        # self.last = nn.Conv2d(n_prev, number_of_classes, kernel_size=1, stride=1, padding=0)
        # self.model_output = nn.Conv2d(number_of_classes,2, kernel_size=1,padding=0,dilation=1,stride=1,bias=False)
        self.model_output = nn.Conv2d(32,number_of_classes, kernel_size=1,padding=0,dilation=1,stride=1, bias=False)
        # self.softmax = SoftmaxAnnealedMean()
        # self.ab_output = nn.Conv2d(number_of_classes, 2, kernel_size=1, padding=0, dilation=1, stride=1, bias=False)
        # self.upsample4 = nn.Upsample(scale_factor=4, mode='bilinear')

    def forward(self, x, isInference:bool=False):
        x = nn.ReLU()(self.conv1(x))
        x = nn.ReLU()(self.conv2(x))
        x = nn.ReLU()(self.conv3(x))
        x = nn.ReLU()(self.conv4(x))
        x = nn.ReLU()(self.conv5(x))
        x = nn.ReLU()(self.conv6(x))
        x = nn.ReLU()(self.conv7(x))
        x = nn.ReLU()(self.conv8(x))
        x = nn.ReLU()(self.conv9(x))
        x = self.upsample1(x)
        x = nn.ReLU()(self.conv10(x))
        x = self.upsample2(x)
        x = nn.ReLU()(self.conv11(x))
        # x = self.tanh(self.conv12(x))
        x = self.upsample3(x)
        x = self.model_output(x)
        return x
        # if not isInference:
        #     return x
        # else:
        #     return self.upsample4(self.ab_output(self.softmax(x)))

In [28]:
model = ColorizerModel(number_of_classes=num_classes)

In [29]:
test_input=torch.rand((16,1,224,224),dtype=torch.float32)

In [30]:
conv1_output = nn.ReLU()(model.conv1(test_input))
conv2_output = nn.ReLU()(model.conv2(conv1_output))
conv3_output = nn.ReLU()(model.conv3(conv2_output))
conv4_output = nn.ReLU()(model.conv4(conv3_output))
conv5_output = nn.ReLU()(model.conv5(conv4_output))
conv6_output = nn.ReLU()(model.conv6(conv5_output))
conv7_output = nn.ReLU()(model.conv7(conv6_output))
conv8_output = nn.ReLU()(model.conv8(conv7_output))
conv9_output = nn.ReLU()(model.conv9(conv8_output))
upsample1_output = model.upsample1(conv9_output)
conv10_output = nn.ReLU()(model.conv10(upsample1_output))
upsample2_output = model.upsample2(conv10_output)
conv11_output = nn.ReLU()(model.conv11(upsample2_output))
upsample3_output = model.upsample3(conv11_output)
model_output = model.model_output(upsample3_output)

In [31]:
print("conv1_output has output of shape:\t" , conv1_output.shape)
print("conv2_output has output of shape:\t" , conv2_output.shape)
print("conv3_output has output of shape:\t" , conv3_output.shape)
print("conv4_output has output of shape:\t" , conv4_output.shape)
print("conv5_output has output of shape:\t" , conv5_output.shape)
print("conv6_output has output of shape:\t" , conv6_output.shape)
print("conv7_output has output of shape:\t" , conv7_output.shape)
print("conv8_output has output of shape:\t" , conv8_output.shape)
print("conv9_output has output of shape:\t" , conv9_output.shape)
print("upsample1_output has output of shape:\t" , upsample1_output.shape)
print("conv10_output has output of shape:\t" , conv10_output.shape)
print("upsample2_output has output of shape:\t" , upsample2_output.shape)
print("conv11_output has output of shape:\t" , conv11_output.shape)
print("upsample3_output has output of shape:\t" , upsample3_output.shape)
print("model_output has output of shape:\t" , model_output.shape)

conv1_output has output of shape:	 torch.Size([16, 64, 224, 224])
conv2_output has output of shape:	 torch.Size([16, 64, 112, 112])
conv3_output has output of shape:	 torch.Size([16, 128, 112, 112])
conv4_output has output of shape:	 torch.Size([16, 128, 56, 56])
conv5_output has output of shape:	 torch.Size([16, 256, 56, 56])
conv6_output has output of shape:	 torch.Size([16, 256, 28, 28])
conv7_output has output of shape:	 torch.Size([16, 512, 28, 28])
conv8_output has output of shape:	 torch.Size([16, 256, 28, 28])
conv9_output has output of shape:	 torch.Size([16, 128, 28, 28])
upsample1_output has output of shape:	 torch.Size([16, 128, 56, 56])
conv10_output has output of shape:	 torch.Size([16, 64, 56, 56])
upsample2_output has output of shape:	 torch.Size([16, 64, 112, 112])
conv11_output has output of shape:	 torch.Size([16, 32, 112, 112])
upsample3_output has output of shape:	 torch.Size([16, 32, 224, 224])
model_output has output of shape:	 torch.Size([16, 313, 224, 224])


# Loss function

In [32]:
from torch.nn.functional import cross_entropy
from scipy.ndimage import gaussian_filter1d
class ReweightedCrossEntropy(torch.nn.Module):
    def __init__(self, Q_value:int, class_weights_probs:np.ndarray, lambda_value=0.5, sigma_value=5, device='cpu'):
        super(ReweightedCrossEntropy, self).__init__()
        self.lambda_value = lambda_value
        self.sigma_value = sigma_value
        self.Q_value = Q_value
        self.class_weights_probs = class_weights_probs
        self.device =device

    def forward(self, model_predictions: torch.Tensor, ground_truth: torch.Tensor):
        """
        Metoda uzima predikcije modela, koji su nenormalizovani logiti, oblika (N, C, d1, d2 ... dK), gde je K>=1, gde je C broj klasa, a N batch size i daje reweighted cross entropy loss i istinitosne vrednosti oblika (N,d1,d2 ... dK), gde je K>=1, gde je svaka vrednost u opsegu [0,C). 

        Parameters
        ----------
        model_predictions : torch.Tensor
            Predikcije koje daje model(nenormalizovani logiti), oblika (N, C, d1, d2 ... dK), gde je K>=1
        ground_truth : torch.Tensor
            Konkretan tenzor klasa za dati piksel, sadrzi **indekse** klasa, tj. svaka vrednost je [0,C), oblika (N, d1, d2 ... dK), gde je K>=1. 
        """
        smoothed_distribution = gaussian_filter1d(self.class_weights_probs, sigma=self.sigma_value)
        w_value = ( (1-self.lambda_value) * smoothed_distribution + (self.lambda_value/self.Q_value) ) ** -1

        return cross_entropy(model_predictions,ground_truth,torch.as_tensor(w_value, device=self.device, dtype=torch.float32))

# Early stopping

In [33]:
class EarlyStopping(object):
    def __init__(self, mode='min', min_delta=0, patience=10, percentage=False, also_use_timer=False, seconds_to_terminate:int=60*60):
        self.mode = mode
        self.min_delta = min_delta
        self.patience = patience
        self.best = None
        self.num_bad_epochs = 0
        self.is_better = None
        self.also_use_timer=also_use_timer
        self._init_is_better(mode, min_delta, percentage)

        if patience == 0:
            self.is_better = lambda a, b: True
            self.step = lambda a: False

        if also_use_timer:
            self.start_time=time.perf_counter()
            self.end_time = 0
            self.time_compare = lambda start,end: end-start >= seconds_to_terminate # NOTE Terminate after an hour
        else:
            self.start_time=None
            self.end_time=None
            self.time_compare = lambda start,end: False

    def step(self, metrics):
        if self.best is None:
            self.best = metrics
            return False

        if torch.is_tensor(metrics):
            if torch.isnan(metrics):
                return True
        elif type(metrics) == float and math.isnan(metrics):
              return True

        if self.is_better(metrics, self.best):
            self.num_bad_epochs = 0
            self.best = metrics
        else:
            self.num_bad_epochs += 1

        if self.num_bad_epochs >= self.patience:
            print('terminating because of early stopping!')
            return True

        return False

    def time_ran_out(self):
        if self.time_compare(self.start_time, self.end_time):
            print("Terminating because of training time limit.")
            return True
        return False

    def _init_is_better(self, mode, min_delta, percentage):
        if mode not in {'min', 'max'}:
            raise ValueError('mode ' + mode + ' is unknown!')
        if not percentage:
            if mode == 'min':
                self.is_better = lambda a, best: a < best - min_delta
            if mode == 'max':
                self.is_better = lambda a, best: a > best + min_delta
        else:
            if mode == 'min':
                self.is_better = lambda a, best: a < best - (
                            best * min_delta / 100)
            if mode == 'max':
                self.is_better = lambda a, best: a > best + (
                            best * min_delta / 100)

# Functions for training and evaluating a model

In [34]:
def evaluate(model: nn.Module, validation: DataLoader, device, metric, is_called_from_training=False):
    model.eval()
    fid = [] 
    for step, batch in enumerate(validation):
        with torch.no_grad():
            inputs, targets = batch
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)

            metric.update(torch.as_tensor(convert_lab_to_rgb(torch.cat( (inputs,targets*128), dim=1).cpu().numpy(),denormalize=True),dtype=torch.uint8), real=True)
            metric.update(torch.as_tensor(convert_lab_to_rgb(torch.cat( (inputs,outputs*128), dim=1).cpu().numpy(),denormalize=True),dtype=torch.uint8), real=False)
            fid.append(metric.compute().item())
    model.train()
    del batch
    collect()
    torch.cuda.empty_cache()
    return fid

def fit(model: nn.Module, optimizer: optim.Optimizer, training:DataLoader, validation: DataLoader, scheduler: lr_scheduler.LRScheduler, metric_for_early_stopping,  epochs:int=50, loss_fn=nn.MSELoss(), gradient_accumulation_steps:int=8,enable_early_stopping:bool=True,patience:int=7,early_stopping_mode:str='min',delta_for_early_stopping:float=0,best:float=None,also_use_timer_for_early_stopping:bool=False, seconds_for_early_stopping:int=60*60, device:str='cpu', epoch_start:int=0, loss=None, shouldEvaluate:bool = True):
    """
    Trenira/fituje model.

    Parameters
    ----------
    model : nn.Module
        Ovo je objekat instanciranog modela kojeg treniramo
    optimizer : optim.Optimizer
        Optimizator parametara `model` koje koristimo
    training : DataLoader
        DataLoader za trening
    validation : DataLoader
        DataLoader za validaciju
    epochs : int, optional
        Broj epoha prilikom treninga
    loss_fn : optional
        Funkcija za generisanja loss-a tokom treninga `model`-a.
    scheduler : LRSCheduler 
        Scheduler za `learning_rate` 
    gradient_accumulation_steps : int, optional
        Koliko step-ova akumuliramo gradijente pre nego sto uradimo apdejt vejtova. Ako ne zelimo akumuliranje gradijenata, setovati ovaj parametar na 1.
    early_stopping_mode : str, optional
        Rezim rada early stopping mehanizma(moze biti `min` ili `max`)
    patience : int, optional
        Koliko koraka u EarlyStoppingu tolerisemo pre nego sto prekinemo trening
    delta_for_early_stopping : float, optional
        Tolerancija odstupanja performansi za early stopping
    metric_for_early_stopping : str, optional
        Koju metriku cemo koristiti za early stopping. 
    best : float, optional
        Najbolji rezultat koji je model postigao. Podrazumevano nema, ako instanciramo model od 0.
    also_use_timer_for_early_stopping : bool, optional
        Da li se koristi i tajmer za early stopping(ako npr. zelimo da trening traje odredjeno vreme)
    device : {'cpu', 'cuda'}
        Na kojem uredjaju zelimo da se vrsi trening.
    epoch_start : int=0
        Od koje epohe poceti trening, koristi se samo ako nastavljamo od checkpointa.
    loss 
        Koji je loss bio na poslednjoj sacuvanoj epohi?
    """
    # model = model.to(device)

    trainingSteps = epochs * len(training)
    
    if enable_early_stopping:
        earlyStopping = EarlyStopping(patience=min(epochs, patience), mode=early_stopping_mode, min_delta=delta_for_early_stopping,also_use_timer=also_use_timer_for_early_stopping, seconds_to_terminate=seconds_for_early_stopping)
    best = best
    
    progress_bar = tqdm(range(trainingSteps))

    model.train()
    completed_steps = 0
    # Ovo navodno ubrzava
    torch.backends.cudnn.benchmark = True
    """
    Reason for turning off above:

    Setting torch.backends.cudnn.benchmark = True before the training loop can accelerate the computation. Because the performance of cuDNN algorithms to compute the convolution of different kernel sizes varies, the auto-tuner can run a benchmark to find the best algorithm (current algorithms are [these](https://github.com/pytorch/pytorch/blob/dab5e2a23ed387046d99f825e0d9a45bd58fccaa/aten/src/ATen/native/cudnn/Conv_v7.cpp#L268-L275), [these](https://github.com/pytorch/pytorch/blob/dab5e2a23ed387046d99f825e0d9a45bd58fccaa/aten/src/ATen/native/cudnn/Conv_v7.cpp#L341-L346), and [these](https://github.com/pytorch/pytorch/blob/dab5e2a23ed387046d99f825e0d9a45bd58fccaa/aten/src/ATen/native/cudnn/Conv_v7.cpp#L413-L418)). It's recommended to use turn on the setting when your input size doesn't change often. If the input size changes often, the auto-tuner needs to benchmark too frequently, which might hurt the performance. It can speed up by 1.27x to 1.70x for forward and backward propagation [ref](https://tigress-web.princeton.edu/~jdh4/PyTorchPerformanceTuningGuide_GTC2021.pdf).    
    """ 
    fid_over_training = dict()
    losses = []
    loss_now = loss
    loss_before = None
    for epoch in range(epoch_start, epochs):
        for step, batch in enumerate(training, start=1):
            # outputs = model(**batch)
            # loss = outputs.loss
            inputs, targets = batch
            inputs, targets = inputs.to(device, non_blocking=True), targets.to(device, non_blocking=True)
            outputs = model(inputs)
            # print(inputs)
            loss = loss_fn(outputs, targets.long())
            loss_before = loss_now
            loss_now = loss
            losses.append(loss.item())
            loss = loss / gradient_accumulation_steps
            loss.backward()
            progress_bar.update(1)
            if step % gradient_accumulation_steps == 0:
                optimizer.step()
                scheduler.step()
                optimizer.zero_grad(set_to_none=True) # set_to_none ne okida memset funkciju i navodno je to brze
                completed_steps += 1
        evaluation = evaluate(model, validation, device, metric_for_early_stopping, is_called_from_training=True) if shouldEvaluate else best
        if shouldEvaluate:
            evaluation = sum(evaluation) / len(evaluation)
            fid_over_training[epoch] = evaluation
        print(f"Tokom epohe {epoch+1} loss je bio {loss} sa akumuliranjem, tj. {loss*gradient_accumulation_steps} bez akumuliranja gradijenta, learning rate je {scheduler.get_last_lr()}, a evaluacija je dala metriku {evaluation}")
        del batch
        collect()
        torch.cuda.empty_cache() 
        if enable_early_stopping:
            earlyStopping.end_time = time.perf_counter()
        if best is None or evaluation < best or not shouldEvaluate and loss_now < loss_before:
            best = evaluation
            torch.save({
                "model":model.state_dict(),
                f"optimizer_{optimizer.__class__.__name__}" : optimizer.state_dict(),
                f"scheduler_{scheduler.__class__.__name__}" : scheduler.state_dict(),
                "epoch": epoch,
                "loss": loss.item() * gradient_accumulation_steps,
                "best" : best
            },model_weights_path + 'checkpoint.tar')
            # torch.save(model.state_dict(), model_weights_path+'model_weights.pth') # NOTE: Mozda puca
            # torch.save(optimizer.state_dict(), model_weights_path+f'optimizer_{optimizer.__class__.__name__}.pt') # NOTE: Mozda puca
            # torch.save(scheduler.state_dict(), model_weights_path+f'scheduler_{scheduler.__class__.__name__}.pt') # NOTE: Mozda puca

        if enable_early_stopping and (earlyStopping.step(evaluation) or earlyStopping.time_ran_out()):
            break
    torch.backends.cudnn.benchmark = False
    return {"fid":fid_over_training, "losses":losses}

# Training

## Initialization

In [35]:
number_of_epochs = 25
batch_size = 64 

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = ColorizerModel(number_of_classes=num_classes).to(device)
optimizer = Lion(model.parameters(), lr=3.67*0.001)
learning_rate_scheduler = lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=number_of_epochs * len(training_ds), eta_min=0.01)
# optimizer = torch.optim.RMSprop(model.parameters())
# learning_rate_scheduler = lr_scheduler.LinearLR(optimizer=optimizer, start_factor=0.9,end_factor=1/5,total_iters=number_of_epochs * len(training))

for state in optimizer.state.values():
    for k,v in state.items():
        if isinstance(v, torch.Tensor):
            state[k] = v.to(device)

#NOTE: menjaj ovo ako hoces da ucitas weightove
use_pretrained_weights = False 
# training = DataLoader(training_ds, batch_size=batch_size, shuffle=True, pin_memory=True)
# validation = DataLoader(validation_ds, batch_size=int(batch_size/4), shuffle=True, pin_memory=True)
training = DataLoader(training_ds, batch_size=batch_size, pin_memory=True)
validation = DataLoader(validation_ds, batch_size=batch_size, pin_memory=True)
metric = FrechetInceptionDistance(feature=64, reset_real_features=False)
epoch_start=0
loss_start=None
best_result = None
if use_pretrained_weights:
    checkpoint = torch.load(model_weights_path+"checkpoint.tar", map_location=device)
    model.load_state_dict(checkpoint['model'])
    optimizer.load_state_dict(checkpoint[f'optimizer_{optimizer.__class__.__name__}'])
    for state in optimizer.state.values():
        for key, value in state.items():
            if isinstance(value, torch.Tensor):
                state[key] = value.to(device)
    learning_rate_scheduler.load_state_dict(checkpoint[f'scheduler_{learning_rate_scheduler.__class__.__name__}'])
    # for state in learning_rate_scheduler.state_dict().values():
    #     for key, value in state.items():
    #         if isinstance(value, torch.Tensor):
    #             state[key] = value.to(device)
    epoch_start = checkpoint['epoch']
    loss_start = checkpoint['loss'] 
    best_result = checkpoint['best']
    model.eval()
    # model.load_state_dict(torch.load(model_weights_path+ 'model_weights.pth'))
    # optimizer.load_state_dict(torch.load(model_weights_path + f'optimizer_{optimizer.__class__.__name__}.pt', map_location=device))
    # learning_rate_scheduler.load_state_dict(torch.load(model_weights_path + f'scheduler_{learning_rate_scheduler.__class__.__name__}.pt', map_location=device))

del training_ds, validation_ds, dataset_memory_map
collect()
torch.cuda.empty_cache()

In [36]:
print(epoch_start,loss_start,best_result)

0 None None


In [37]:
# filterwarnings("ignore")
# model.to(device)
# test_real, test_pred = evaluate(model,validation,device,metric)

## Struktura i parametri modela prikazani

In [38]:
print(model)

ColorizerModel(
  (conv1): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv4): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (conv5): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv6): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (conv7): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv8): Conv2d(512, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv9): Conv2d(256, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (upsample1): Upsample(scale_factor=2.0, mode='nearest')
  (conv10): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (upsample2): Upsample(scale_factor=2.0, mode='nearest')
  (conv11): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (ups

In [39]:
total_params=0
for name, parameter in model.named_parameters():
    print(f"Parametar:\t{name},\tTip:\t{parameter.dtype},\tVelicina:\t{parameter.numel()}")
    total_params+=parameter.numel()
print("-"*15,"\nUkupno parametara:\t",total_params)

Parametar:	conv1.weight,	Tip:	torch.float32,	Velicina:	576
Parametar:	conv1.bias,	Tip:	torch.float32,	Velicina:	64
Parametar:	conv2.weight,	Tip:	torch.float32,	Velicina:	36864
Parametar:	conv2.bias,	Tip:	torch.float32,	Velicina:	64
Parametar:	conv3.weight,	Tip:	torch.float32,	Velicina:	73728
Parametar:	conv3.bias,	Tip:	torch.float32,	Velicina:	128
Parametar:	conv4.weight,	Tip:	torch.float32,	Velicina:	147456
Parametar:	conv4.bias,	Tip:	torch.float32,	Velicina:	128
Parametar:	conv5.weight,	Tip:	torch.float32,	Velicina:	294912
Parametar:	conv5.bias,	Tip:	torch.float32,	Velicina:	256
Parametar:	conv6.weight,	Tip:	torch.float32,	Velicina:	589824
Parametar:	conv6.bias,	Tip:	torch.float32,	Velicina:	256
Parametar:	conv7.weight,	Tip:	torch.float32,	Velicina:	1179648
Parametar:	conv7.bias,	Tip:	torch.float32,	Velicina:	512
Parametar:	conv8.weight,	Tip:	torch.float32,	Velicina:	1179648
Parametar:	conv8.bias,	Tip:	torch.float32,	Velicina:	256
Parametar:	conv9.weight,	Tip:	torch.float32,	Velicina

## Trening

In [ ]:
loss_fn = ReweightedCrossEntropy(Q_value=num_classes,class_weights_probs=probs, device=device)
for step, batch in enumerate(training, start=1):
    # outputs = model(**batch)
    # loss = outputs.loss
    inputs, targets = batch
    inputs, targets = inputs.to(device, non_blocking=True), targets.to(device, non_blocking=True)
    # print("Nakon kastovanja u devajs")
    outputs = model(inputs)
    # print("Nakon modela")
    # print(inputs)
    loss = loss_fn(outputs, torch.randint(0,251,(64,224,224),device=device))
    print("Nakon lossa")
    break

In [ ]:
mappings

In [ ]:
targets.long().

In [ ]:
cross_entropy(outputs, torch.randint(0,251,(64,224,224),device=device))

In [ ]:
loss = cross_entropy(outputs,targets.long())

In [ ]:
cross_entropy(model_predictions,ground_truth,torch.as_tensor(w_value, device=self.device, dtype=torch.float32))

In [ ]:
filterwarnings("ignore")
fit(model=model,optimizer=optimizer,training=training, validation=validation,scheduler=learning_rate_scheduler,epochs=number_of_epochs,device=device, gradient_accumulation_steps=12, metric_for_early_stopping=metric, enable_early_stopping=True,early_stopping_mode='min',patience=4,epoch_start=epoch_start, loss=loss_start, shouldEvaluate=False, best=best_result, loss_fn=ReweightedCrossEntropy(Q_value=num_classes,class_weights_probs=probs,device=device))

# Test

In [ ]:
# TODO...
# test = ImageDataset(dataset_memory_map[test_indices], transform=transform)

# Inference

## Endpoint

In [ ]:
def colorize(image: np.ndarray, print_image_inline=False) -> np.ndarray:
    """
    Ova metoda kolorizuje sliku koja joj je prosledjena.

    Parameters
    ----------
    image : np.ndarray
        Slika u RGB ili L*a*b* formatu(za sad).

    print_image_inline : boolean=False
        Da li da se slika prikaze inline ispod celije.

    Returns
    -------
    
    """
    return

## Upotreba

In [ ]:
# model.eval()
# with torch.no_grad():
#     output = model(torch.tensor(X).float().to(device)).cpu().numpy()
#     output *= 128
#     rgb_img = convert_lab_to_rgb(np.concatenate((X,output), axis=1),denormalize=True)
#     imsave("img_result.png", rgb_img[0].reshape(400,400,3))
#     imsave("img_result_gray_version.png", (255*rgb2gray(rgb_img[0].reshape(400,400,3))).astype(np.uint8))
# model.train()